name: Build and Publish Uniflow Release

on:
  push:
    tags:
      - 'v*'
  
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # get the history and the tags
      
      - name: Determine Release Tag
        id: release
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            RELEASE_TAG=$(git describe --tags --abbrev=0)
            echo "Manual workflow run"
            echo "Latest tag ${RELEASE_TAG}"
          else
            RELEASE_TAG="${GITHUB_REF_NAME}"
            echo "Automatic workflow run"
            echo "Triggered by tag ${RELEASE_TAG}"
          fi

          echo "release_tag=${RELEASE_TAG}" >> "$GITHUB_OUTPUT"

      - name: Create Uniflow Release
        uses: softprops/action-gh-release@v2
        with:
          #use the tag name (example v1.0.0) for release
          tag_name: ${{ steps.release.outputs.release_tag }}
          name: Release ${{ steps.release.outputs.release_tag }}
          
          # GitHub automatically generates the release notes here based on the commits.
          # However, since we already have a CHANGELOG.md file, this line reads your completed changelog.
          body_path: CHANGELOG.md 
          
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}